eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: Happy!23
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    discovery:
      enabled: true
server:
  port: 8086
